excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://tpinilla.github.io
name: Mantén calma y habla español
description: Steps and misteps of a veteran teacher taking on a new classroom role.
author: profesora pinilla
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 